<?php

require_once 'Twig/Autoloader.php';
Twig_Autoloader::register();

function mvc_node_view($node, $view_mode, $langcode) {
  $wrapper = entity_metadata_wrapper('event', $node);
  MVCRouter::dispatch($node, $wrapper);
  // print_r($node->type);
  // print_r($wrapper->field_location->value());
  //die();
  // $wrapper = entity_metadata_wrapper('node', $node);
  // dprint_r($wrapper);
  // die();
  // if (empty($node->field_slug)) {
  //   return;
  // }
  // $c = new BaseNodeController();
  // $c->dispatch($wrapper);
}


class Dispatcher {

  public function dispatch($node) {

  }

}

class MVCRouter {

  protected static $_routes = array(
    'node' => array(
      'event' => 'EventController'
    )
  );

  public static function dispatch($node, $wrapper) {
    $content_type = $node->type;    
    if (isset(self::$_routes['node'][$content_type])) {      
      $controller_class = self::$_routes['node'][$content_type];
      $controller = new $controller_class;
      $output = $controller->get($node, $wrapper);
      echo $output;
      exit();
    }
  }

}


class MvcController {

  protected $_twig;

  public function __construct() {
    $loader = new Twig_Loader_Filesystem('/Users/fabio/Code/drupal-mvc/templates');
    $this->_twig = new Twig_Environment($loader, array(
        //'cache' => '/Users/fabio/Code/drupal-mvc/twig_cache',
    ));
    $function = new Twig_SimpleFunction('url', function ($path = NULL, array $options = array()) {
      return url($path, $options);
    });
    $this->_twig->addFunction($function);
  }

  public function dispatch($node) {
    $method = 'node_' . $node->field_slug->value();
    if (!method_exists($this, $method)) {
      return;
    }
    $output = call_user_func_array(array($this, $method), array($node));
    echo $output;
    exit();
  }

  public function beforeRender(array $context) {
    return $context;
  }

  public function render($template, $context = array()) {
    $context = $this->beforeRender($context);
    return $this->_twig->render($template, $context);
  }

}


class BaseNodeController extends MvcController {

  public function beforeRender(array $context) {
    $context = parent::beforeRender($context);
    $context['main_menu'] = menu_navigation_links('main-menu');
    return $context;
  }

  public function node_about_us($node) {
    $view = views_get_view('events');
    $view->set_display('last_events');
    $view->execute();
    $events = $view->result;
    
    $context = array(
      'name' => 'Fabio',
      'node' => $node,
      'events' => $events
    );
    return $this->render('index.html', $context);
  }

  public function node_contacts($node) {
    $context = array(
      'node' => $node,
    );
    return $this->render('contacts.html', $context);
  }

}

class EventController extends MvcController {

  // public function dispatch($node) {
  //   $output = $this->view($node);
  //   echo $output;
  //   exit();
  // }

  public function get($node, $wrapper) {
    $context = array(
      'node' => $wrapper,
    );
    return $this->render('events/detail.html', $context);
  }
}